### PR TITLE
Adding commands helpful when deploying to AWS EB

### PR DESCRIPTION
**Pull request by stig**
I extracted these from Connector's CircleCI config. We've got similar commands / snippets in 3 other projects, and I'm hoping to enable us to kill a lot of duplication in our CircleCI config this way.

### CODE REVIEW

**Review by jeffmacdonald — COMMENTED** [review]
This is beautiful.

**Review by slafs — COMMENTED** [review]
I'm afraid I won't have time to review this properly before my vacation, sorry.

**Comment by stig** [comment]
Enjoy your vacation @slafs :-)

**Comment by stig** [comment]
I added a couple more commands, including one to tie them all together. Pretty happy with it :-)

**Comment by stig** [comment]
I'm going to close this PR on the grounds that it steals my attention every time I go through my list of open PRs. (Multiple times a day.) Feel free to re-open if you want to use this work. The copyright is LaterPay's, as I created it while working there.

**Pull request closed without merging**
